[workspace]
members = [
    "interface",
    "plugin-simple"
]


[package]
name = "plugin-system"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.7"
interface = { path = "interface" }
log = "0.4"
env_logger = "0.10"
